# Generated by Django 2.0.4 on 2018-04-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_lead', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_lead_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_lead_1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Home_sub_titile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_sub_titile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Home_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Header_text',
            new_name='Home_tagline',
        ),
        migrations.RenameField(
            model_name='home_tagline',
            old_name='header_text',
            new_name='Home_tagline',
        ),
    ]
