# Generated by Django 2.0.4 on 2018-04-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20180421_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_title',
            name='Home_title',
        ),
        migrations.AddField(
            model_name='home_title',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Home Title'),
        ),
    ]
