# Generated by Django 2.0.4 on 2018-04-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20180422_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100, verbose_name='Contact Lead line 1')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLead1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100, verbose_name='Contact Lead line 2')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSubtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Home Subtitle')),
            ],
        ),
        migrations.CreateModel(
            name='HomeTagLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200, verbose_name='Home Tag Line')),
            ],
        ),
        migrations.CreateModel(
            name='HomeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Home Title')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact_lead',
        ),
        migrations.DeleteModel(
            name='Contact_lead_1',
        ),
        migrations.DeleteModel(
            name='Home_subtitile',
        ),
        migrations.DeleteModel(
            name='Home_tagline',
        ),
        migrations.DeleteModel(
            name='Home_title',
        ),
    ]
