# Generated by Django 2.0.4 on 2018-04-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20180422_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Заголовок правый')),
                ('text', models.CharField(blank=True, max_length=250, verbose_name='Текст правого блока')),
                ('name_secod', models.CharField(blank=True, max_length=50, verbose_name='Заголовок левый')),
                ('text_second', models.CharField(blank=True, max_length=250, verbose_name='Текс левого блока')),
            ],
            options={
                'verbose_name': 'Описание',
            },
        ),
    ]
