# Generated by Django 2.0.4 on 2018-04-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_aboutme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'Обо мне.', 'verbose_name_plural': 'Обо мне'},
        ),
    ]
