# Generated by Django 2.0.4 on 2018-04-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20180422_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=100, verbose_name='Текст описания')),
                ('img_name_one', models.CharField(blank=True, max_length=20, verbose_name='Заголовок первый')),
                ('img_text_one', models.CharField(blank=True, max_length=200, verbose_name='Текст описания')),
                ('img_name_two', models.CharField(blank=True, max_length=20, verbose_name=' Заголовок второй')),
                ('img_text_two', models.CharField(blank=True, max_length=200, verbose_name='Текст описания')),
                ('img_name_three', models.CharField(blank=True, max_length=20, verbose_name='Заголовок третий')),
                ('img_text_three', models.CharField(blank=True, max_length=200, verbose_name='Текст описания')),
                ('img_name_four', models.CharField(blank=True, max_length=20, verbose_name='Заголовок четвертый')),
                ('img_text_four', models.CharField(blank=True, max_length=200, verbose_name='Текст описания')),
            ],
            options={
                'verbose_name': 'О сайте',
                'verbose_name_plural': 'О сайтах',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(blank=True, max_length=100, verbose_name='Строка 1')),
                ('line_two', models.CharField(blank=True, max_length=100, verbose_name='Строка 2')),
                ('line_three', models.CharField(blank=True, max_length=100, verbose_name='Строка 3')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Строка 1')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Строка 2')),
                ('tagline', models.CharField(max_length=50, verbose_name='Строка 3')),
            ],
            options={
                'verbose_name': 'Домашняя страница',
                'verbose_name_plural': 'Домашние страницы',
            },
        ),
        migrations.DeleteModel(
            name='ContactLead',
        ),
        migrations.DeleteModel(
            name='ContactLead1',
        ),
        migrations.DeleteModel(
            name='HomeSubtitle',
        ),
        migrations.DeleteModel(
            name='HomeTagLine',
        ),
        migrations.DeleteModel(
            name='HomeTitle',
        ),
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'Обо мне', 'verbose_name_plural': 'Обо мне'},
        ),
    ]
