# Generated by Django 2.0.4 on 2018-04-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_auto_20180422_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Строка 2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='tagline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Строка 3'),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Строка 1'),
        ),
    ]
