# Generated by Django 2.0.4 on 2018-04-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_auto_20180422_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Line one')),
            ],
        ),
        migrations.CreateModel(
            name='LineThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Line Three')),
            ],
        ),
        migrations.CreateModel(
            name='LineTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Line Two')),
            ],
        ),
        migrations.AlterModelOptions(
            name='home',
            options={},
        ),
        migrations.RemoveField(
            model_name='home',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='home',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='home',
            name='title',
        ),
        migrations.AddField(
            model_name='home',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Home page'),
        ),
        migrations.AddField(
            model_name='linetwo',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Home'),
        ),
        migrations.AddField(
            model_name='linethree',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Home'),
        ),
        migrations.AddField(
            model_name='lineone',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Home'),
        ),
    ]
