# Generated by Django 2.0.4 on 2018-04-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_auto_20180423_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineone',
            name='home',
        ),
        migrations.RemoveField(
            model_name='linethree',
            name='home',
        ),
        migrations.RemoveField(
            model_name='linetwo',
            name='home',
        ),
        migrations.RemoveField(
            model_name='home',
            name='name',
        ),
        migrations.AddField(
            model_name='home',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Строка 2'),
        ),
        migrations.AddField(
            model_name='home',
            name='tagline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Строка 3'),
        ),
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Строка 1'),
        ),
        migrations.DeleteModel(
            name='LineOne',
        ),
        migrations.DeleteModel(
            name='LineThree',
        ),
        migrations.DeleteModel(
            name='LineTwo',
        ),
    ]
