# Generated by Django 2.0.4 on 2018-04-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_auto_20180423_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Домашняя сраница', 'verbose_name_plural': 'Домашние сраницы'},
        ),
    ]
