# Generated by Django 2.0.4 on 2018-04-25 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_auto_20180423_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsite',
            old_name='text',
            new_name='about_text',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='title',
            new_name='about_title',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='img_name_four',
            new_name='name_four',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='img_name_one',
            new_name='name_one',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='img_name_three',
            new_name='name_three',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='img_name_two',
            new_name='name_two',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='img_text_four',
            new_name='text_four',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='img_text_one',
            new_name='text_one',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='img_text_three',
            new_name='text_three',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='img_text_two',
            new_name='text_two',
        ),
    ]
