# Generated by Django 2.0.4 on 2018-04-25 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_auto_20180425_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='name_secod',
            new_name='name_second',
        ),
    ]
