# Generated by Django 2.0.4 on 2018-04-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_auto_20180425_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsite',
            old_name='name_four',
            new_name='namefour',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='name_one',
            new_name='nameone',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='name_three',
            new_name='namethree',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='name_two',
            new_name='nametwo',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='about_text',
            new_name='sitetext',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='about_title',
            new_name='sitetitle',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='text_four',
            new_name='textfour',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='text_one',
            new_name='textone',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='text_three',
            new_name='textthree',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='text_two',
            new_name='texttwo',
        ),
    ]
