# Generated by Django 2.0.4 on 2018-04-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_auto_20180425_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsite',
            old_name='namefour',
            new_name='name_four',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='nameone',
            new_name='name_one',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='namethree',
            new_name='name_three',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='nametwo',
            new_name='name_two',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='sitetext',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='textfour',
            new_name='text_four',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='textone',
            new_name='text_one',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='textthree',
            new_name='text_three',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='texttwo',
            new_name='text_two',
        ),
        migrations.RenameField(
            model_name='aboutsite',
            old_name='sitetitle',
            new_name='title',
        ),
    ]
